spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products-service
    username: postgres
    password: mysecretpassword
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.xml

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  logging:
    level:
      org.springframework: debug

  server:
    error:
      include-message: always
